export const genreOptions = [
  { value: "alternative", label: "Alternative" },
  { value: "alternative_rock", label: "Alternative Rock" },
  { value: "alternative_and_rock_latino", label: "Alternative & Rock Latino" },
  { value: "anime", label: "Anime" },
  { value: "baladas_y_boleros", label: "Baladas Y Boleros" },
  { value: "big_band", label: "Big Band" },
  { value: "blues", label: "Blues" },
  { value: "brazilian", label: "Brazilian" },
  { value: "c_pop", label: "C-Pop" },
  { value: "cantopop_hk_pop", label: "Cantopop/HK - Pop" },
  { value: "childrens", label: "Children's" },
  { value: "chinese", label: "Chinese" },
  { value: "christian", label: "Christian" },
  { value: "classical", label: "Classical" },
  { value: "comedy", label: "Comedy" },
  { value: "contemporary_latin", label: "Contemporary Latin" },
  { value: "country", label: "Country" },
  { value: "dance", label: "Dance" },
  { value: "easy_listening", label: "Easy Listening" },
  { value: "educational", label: "Educational" },
  { value: "electronic", label: "Electronic" },
  { value: "enka", label: "Enka" },
  { value: "experimental", label: "Experimental" },
  { value: "fitness_and_workout", label: "Fitness & Workout" },
  { value: "folk", label: "Folk" },
  { value: "french_pop", label: "French Pop" },
  { value: "german_pop", label: "German Pop" },
  { value: "german_folk", label: "German Folk" },
  { value: "hip_hop_rap", label: "Hip-Hop/Rap" },
  { value: "holiday", label: "Holiday" },
  { value: "instrumental", label: "Instrumental" },
  { value: "indo_pop", label: "Indo Pop" },
  { value: "inspirational", label: "Inspirational" },
  { value: "indian", label: "Indian" },
  { value: "indian_pop", label: "Indian Pop" },
  { value: "indian_rap", label: "Indian Rap" },
  { value: "indian_folk", label: "Indian Folk" },
  { value: "indian_bollywood", label: "Indian Bollywood" },
  { value: "indian_devotional_and_spiritual", label: "Indian Devotional & Spiritual" },
  { value: "indian_fusion", label: "Indian Fusion" },
  { value: "indian_gazal", label: "Indian Gazal" },
  { value: "indian_classical_vocal", label: "Indian Classical / Vocal" },
  { value: "indian_dance", label: "Indian Dance" },
  { value: "indian_electronic", label: "Indian Electronic" },
  { value: "jazz", label: "Jazz" },
  { value: "j_pop", label: "J-Pop" },
  { value: "k_pop", label: "K-Pop" },
  { value: "karaoke", label: "Karaoke" },
  { value: "latin_jazz", label: "Latin Jazz" },
  { value: "metal", label: "Metal" },
  { value: "new_age", label: "New Age" },
  { value: "opera", label: "Opera" },
  { value: "pop", label: "Pop" },
  { value: "punk", label: "Punk" },
  { value: "r_and_b", label: "R&B" },
  { value: "reggae", label: "Reggae" },
  { value: "reggaeton_y_hip_hop", label: "Reggaeton Y Hip-Hop" },
  { value: "regional_mexicano", label: "Regional Mexicano" },
  { value: "rock", label: "Rock" },
  { value: "salas_y_topical", label: "Salas Y Topical" },
  { value: "soul", label: "Soul" },
  { value: "soundtrack", label: "Soundtrack" },
  { value: "spoken_word", label: "Spoken Word" },
  { value: "thai_pop", label: "Thai Pop" },
  { value: "trot", label: "Trot" },
  { value: "vocal_nostalgia", label: "Vocal/Nostalgia" },
  { value: "world", label: "World" },
];

export const moodOptions = [
  { value: "uplifting", label: "Uplifting" },
  { value: "melancholic", label: "Melancholic" },
  { value: "euphoric", label: "Euphoric" },
  { value: "nostalgic", label: "Nostalgic" },
  { value: "romantic", label: "Romantic" },
  { value: "cinematic", label: "Cinematic" },
  { value: "aggressive", label: "Aggressive" },
  { value: "chill_mellow", label: "Chill / Mellow" },
  { value: "dark_moody", label: "Dark / Moody" },
  { value: "hopeful", label: "Hopeful" },
  { value: "tense_suspenseful", label: "Tense / Suspenseful" },
  { value: "playful_quirky", label: "Playful / Quirky" },
  { value: "energetic_high_tempo", label: "Energetic / High Tempo" },
  { value: "inspirational", label: "Inspirational" },
  { value: "mysterious", label: "Mysterious" },
  { value: "sad_reflective", label: "Sad / Reflective" },
  { value: "spiritual_devotional", label: "Spiritual / Devotional" },
  { value: "groovy_funky", label: "Groovy / Funky" },
  { value: "tribal_rooted", label: "Tribal / Rooted" },
  { value: "anthemic_epic", label: "Anthemic / Epic" },
];

export const languageOptions = [
  { value: "instrumental", label: "Instrumental" },
  { value: "afrikaans", label: "Afrikaans" },
  { value: "albanian", label: "Albanian" },
  { value: "amharic", label: "Amharic" },
  { value: "arabic", label: "Arabic" },
  { value: "aragonese", label: "Aragonese" },
  { value: "armenian", label: "Armenian" },
  { value: "asturian", label: "Asturian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "basque", label: "Basque" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bengali", label: "Bengali" },
  { value: "bhojpuri", label: "Bhojpuri" },
  { value: "bosnian", label: "Bosnian" },
  { value: "breton", label: "Breton" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "catalan", label: "Catalan" },
  { value: "central_kurdish", label: "Central Kurdish" },
  { value: "chinese", label: "Chinese" },
  { value: "corsican", label: "Corsican" },
  { value: "croatian", label: "Croatian" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "dutch", label: "Dutch" },
  { value: "english", label: "English" },
  { value: "english_australia", label: "English (Australia)" },
  { value: "english_canada", label: "English (Canada)" },
  { value: "english_india", label: "English (India)" },
  { value: "english_us", label: "English (US)" },
  { value: "english_uk", label: "English (UK)" },
  { value: "english_new_zealand", label: "English (New Zealand)" },
  { value: "english_south_africa", label: "English (South Africa)" },
  { value: "estenian", label: "Estenian" },
  { value: "fareese", label: "Fareese" },
  { value: "filipino", label: "Filipino" },
  { value: "finnish", label: "Finnish" },
  { value: "french", label: "French" },
  { value: "galician", label: "Galician" },
  { value: "georgian", label: "Georgian" },
  { value: "german", label: "German" },
  { value: "gurani", label: "Gurani" },
  { value: "gujrati", label: "Gujrati" },
  { value: "hausa", label: "Hausa" },
  { value: "hawaiian", label: "Hawaiian" },
  { value: "hebrew", label: "Hebrew" },
  { value: "hindi", label: "Hindi" },
  { value: "hungarian", label: "Hungarian" },
  { value: "icelandic", label: "Icelandic" },
  { value: "indonesian", label: "Indonesian" },
  { value: "interlingua", label: "Interlingua" },
  { value: "irish", label: "Irish" },
  { value: "italian", label: "Italian" },
  { value: "japanese", label: "Japanese" },
  { value: "kannada", label: "Kannada" },
  { value: "kazakh", label: "Kazakh" },
  { value: "khmer", label: "Khmer" },
  { value: "koren", label: "Koren" },
  { value: "kurdish", label: "Kurdish" },
  { value: "kyrgyz", label: "Kyrgyz" },
  { value: "lao", label: "Lao" },
  { value: "latin", label: "Latin" },
  { value: "latvian", label: "Latvian" },
  { value: "lingala", label: "Lingala" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malay", label: "Malay" },
  { value: "malayalam", label: "Malayalam" },
  { value: "maltese", label: "Maltese" },
  { value: "marathi", label: "Marathi" },
  { value: "mongolian", label: "Mongolian" },
  { value: "nagpuri", label: "Nagpuri" },
  { value: "nepali", label: "Nepali" },
  { value: "norwegian", label: "Norwegian" },
  { value: "occitan", label: "Occitan" },
  { value: "odia", label: "Odia" },
  { value: "oromo", label: "Oromo" },
  { value: "pashto", label: "Pashto" },
  { value: "persian", label: "Persian" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "punjabi", label: "Punjabi" },
  { value: "quechua", label: "Quechua" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "sainthili", label: "Sainthili" },
  { value: "scottish", label: "Scottish" },
  { value: "serbian", label: "Serbian" },
  { value: "sindhi", label: "Sindhi" },
  { value: "shono", label: "Shono" },
  { value: "sinhala", label: "Sinhala" },
  { value: "slovak", label: "Slovak" },
  { value: "slovernian", label: "Slovernian" },
  { value: "somali", label: "Somali" },
  { value: "spanish", label: "Spanish" },
  { value: "sundanese", label: "Sundanese" },
  { value: "swahili", label: "Swahili" },
  { value: "swedish", label: "Swedish" },
  { value: "tajik", label: "Tajik" },
  { value: "tamil", label: "Tamil" },
  { value: "tatar", label: "Tatar" },
  { value: "telugu", label: "Telugu" },
  { value: "thai", label: "Thai" },
  { value: "tigrinya", label: "Tigrinya" },
  { value: "tongan", label: "Tongan" },
  { value: "turkish", label: "Turkish" },
  { value: "turkmen", label: "Turkmen" },
  { value: "twi", label: "Twi" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "urdu", label: "Urdu" },
  { value: "uyghur", label: "Uyghur" },
  { value: "uzbek", label: "Uzbek" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "walloon", label: "Walloon" },
  { value: "wetish", label: "Wetish" },
  { value: "western_frisian", label: "Western Frisian" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yiddish", label: "Yiddish" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zulu", label: "Zulu" },
];

export const themeOptions = [
  { value: "love_romance", label: "Love & Romance" },
  { value: "heartbreak_healing", label: "Heartbreak & Healing" },
  { value: "rebellion_resistance", label: "Rebellion & Resistance" },
  { value: "celebration_party", label: "Celebration & Party" },
  { value: "spiritual_devotional", label: "Spiritual & Devotional" },
  { value: "coming_of_age", label: "Coming-of-Age" },
  { value: "friendship_brotherhood", label: "Friendship & Brotherhood" },
  { value: "nature_environment", label: "Nature & Environment" },
  { value: "festival_tradition", label: "Festival & Tradition" },
  { value: "identity_self_discovery", label: "Identity & Self-Discovery" },
  { value: "urban_life_hustle", label: "Urban Life & Hustle" },
  { value: "nostalgia_memory", label: "Nostalgia & Memory" },
  { value: "hope_resilience", label: "Hope & Resilience" },
  { value: "journey_travel", label: "Journey & Travel" },
  { value: "family_legacy", label: "Family & Legacy" },
  { value: "social_justice_awareness", label: "Social Justice & Awareness" },
  { value: "fantasy_imagination", label: "Fantasy & Imagination" },
  { value: "ritual_culture", label: "Ritual & Culture" },
  { value: "empowerment_confidence", label: "Empowerment & Confidence" },
  { value: "mystery_suspense", label: "Mystery & Suspense" },
];

export const vocalsPresentOptions = [
  { value: "true", label: 'Yes' },
  { value: "false", label: 'No' },
];

export const syncClearedOptions = [
  { value: "true", label: 'Yes' },
  { value: "false", label: 'No' },
  { value: 'unsure', label: 'Unsure (Request assistance)' },
];

export const storeOptions = [
  { value: 'select_all', label: 'Select All' },
  { value: 'Spotify', label: 'Spotify' },
  { value: 'Apple Music', label: 'Apple Music' },
  { value: 'JioSaavn', label: 'JioSaavn' },
  { value: 'Amazon Music', label: 'Amazon Music' },
];

export const masterRightsOptions = [
  { value: 'artist', label: 'Artist' },
  { value: "label", label: "Label" },
  { value: "distributor", label: "Distributor" },
  { value: "other", label: "Other" },
];

export const publishingRightsOptions = [
  { value: "artist", label: "Artist" },
  { value: "publisher", label: "Publisher" },
  { value: "co_writer_s", label: "Co-writer(s)" },
  { value: "pro_registered", label: "PRO Registered" },
];

export const territoryOptions = [
  { value: 'afghanistan', label: 'Afghanistan' },
  { value: 'albania', label: 'Albania' },
  { value: 'algeria', label: 'Algeria' },
  { value: 'andorra', label: 'Andorra' },
  { value: 'angola', label: 'Angola' },
  { value: 'antigua_and_barbuda', label: 'Antigua and Barbuda' },
  { value: 'argentina', label: 'Argentina' },
  { value: 'armenia', label: 'Armenia' },
  { value: 'australia', label: 'Australia' },
  { value: 'austria', label: 'Austria' },
  { value: 'azerbaijan', label: 'Azerbaijan' },
  { value: 'bahamas', label: 'Bahamas' },
  { value: 'bahrain', label: 'Bahrain' },
  { value: 'bangladesh', label: 'Bangladesh' },
  { value: 'barbados', label: 'Barbados' },
  { value: 'belarus', label: 'Belarus' },
  { value: 'belgium', label: 'Belgium' },
  { value: 'belize', label: 'Belize' },
  { value: 'benin', label: 'Benin' },
  { value: 'bhutan', label: 'Bhutan' },
  { value: 'bolivia', label: 'Bolivia' },
  { value: 'bosnia_and_herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'botswana', label: 'Botswana' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'brunei', label: 'Brunei' },
  { value: 'bulgaria', label: 'Bulgaria' },
  { value: 'burkina_faso', label: 'Burkina Faso' },
  { value: 'burundi', label: 'Burundi' },
  { value: 'cabo_verde', label: 'Cabo Verde' },
  { value: 'cambodia', label: 'Cambodia' },
  { value: 'cameroon', label: 'Cameroon' },
  { value: 'canada', label: 'Canada' },
  { value: 'central_african_republic', label: 'Central African Republic' },
  { value: 'chad', label: 'Chad' },
  { value: 'chile', label: 'Chile' },
  { value: 'china', label: 'China' },
  { value: 'colombia', label: 'Colombia' },
  { value: 'comoros', label: 'Comoros' },
  { value: 'congo_congo-brazzaville', label: 'Congo (Congo-Brazzaville)' },
  { value: 'costa_rica', label: 'Costa Rica' },
  { value: 'cote_divoire', label: 'Cote d\'Ivoire' },
  { value: 'croatia', label: 'Croatia' },
  { value: 'cuba', label: 'Cuba' },
  { value: 'cyprus', label: 'Cyprus' },
  { value: 'czechia', label: 'Czechia' },
  { value: 'democratic_republic_of_the_united_states_of_america', label: 'Democratic Republic of the United States of America' },
  { value: 'denmark', label: 'Denmark' },
  { value: 'djibouti', label: 'Djibouti' },
  { value: 'dominica', label: 'Dominica' },
  { value: 'dominican_republic', label: 'Dominican Republic' },
  { value: 'ecuador', label: 'Ecuador' },
  { value: 'egypt', label: 'Egypt' },
  { value: 'el_salvador', label: 'El Salvador' },
  { value: 'equatorial_guinea', label: 'Equatorial Guinea' },
  { value: 'eritrea', label: 'Eritrea' },
  { value: 'estonia', label: 'Estonia' },
  { value: 'eswatini_formerly_swaziland', label: 'Eswatini (formerly Swaziland)' },
  { value: 'ethiopia', label: 'Ethiopia' },
  { value: 'fiji', label: 'Fiji' },
  { value: 'finland', label: 'Finland' },
  { value: 'france', label: 'France' },
  { value: 'gabon', label: 'Gabon' },
  { value: 'gambia', label: 'Gambia' },
  { value: 'georgia', label: 'Georgia' },
  { value: 'germany', label: 'Germany' },
  { value: 'ghana', label: 'Ghana' },
  { value: 'greece', label: 'Greece' },
  { value: 'grenada', label: 'Grenada' },
  { value: 'guatemala', label: 'Guatemala' },
  { value: 'guinea', label: 'Guinea' },
  { value: 'guinea-bissau', label: 'Guinea-Bissau' },
  { value: 'guyana', label: 'Guyana' },
  { value: 'haiti', label: 'Haiti' },
  { value: 'honduras', label: 'Honduras' },
  { value: 'hungary', label: 'Hungary' },
  { value: 'iceland', label: 'Iceland' },
  { value: 'india', label: 'India' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'iran', label: 'Iran' },
  { value: 'iraq', label: 'Iraq' },
  { value: 'ireland', label: 'Ireland' },
  { value: 'israel', label: 'Israel' },
  { value: 'italy', label: 'Italy' },
  { value: 'jamaica', label: 'Jamaica' },
  { value: 'japan', label: 'Japan' },
  { value: 'jordan', label: 'Jordan' },
  { value: 'kazakhstan', label: 'Kazakhstan' },
  { value: 'kenya', label: 'Kenya' },
  { value: 'kiribati', label: 'Kiribati' },
  { value: 'kuwait', label: 'Kuwait' },
  { value: 'kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'laos', label: 'Laos' },
  { value: 'latvia', label: 'Latvia' },
  { value: 'lebanon', label: 'Lebanon' },
  { value: 'lesotho', label: 'Lesotho' },
  { value: 'liberia', label: 'Liberia' },
  { value: 'libya', label: 'Libya' },
  { value: 'liechtenstein', label: 'Liechtenstein' },
  { value: 'lithuania', label: 'Lithuania' },
  { value: 'luxembourg', label: 'Luxembourg' },
  { value: 'madagascar', label: 'Madagascar' },
  { value: 'malawi', label: 'Malawi' },
  { value: 'malaysia', label: 'Malaysia' },
  { value: 'maldives', label: 'Maldives' },
  { value: 'mali', label: 'Mali' },
  { value: 'malta', label: 'Malta' },
  { value: 'marshall_islands', label: 'Marshall Islands' },
  { value: 'mauritania', label: 'Mauritania' },
  { value: 'mauritius', label: 'Mauritius' },
  { value: 'mexico', label: 'Mexico' },
  { value: 'micronesia', label: 'Micronesia' },
  { value: 'moldova', label: 'Moldova' },
  { value: 'monaco', label: 'Monaco' },
  { value: 'mongolia', label: 'Mongolia' },
  { value: 'montenegro', label: 'Montenegro' },
  { value: 'morocco', label: 'Morocco' },
  { value: 'mozambique', label: 'Mozambique' },
  { value: 'myanmar_formerly_burma', label: 'Myanmar (formerly Burma)' },
  { value: 'namibia', label: 'Namibia' },
  { value: 'nauru', label: 'Nauru' },
  { value: 'nepal', label: 'Nepal' },
  { value: 'netherlands', label: 'Netherlands' },
  { value: 'new_zealand', label: 'New Zealand' },
  { value: 'nicaragua', label: 'Nicaragua' },
  { value: 'niger', label: 'Niger' },
  { value: 'nigeria', label: 'Nigeria' },
  { value: 'north_korea', label: 'North Korea' },
  { value: 'north_macedonia_formerly_macedonia', label: 'North Macedonia (formerly Macedonia)' },
  { value: 'norway', label: 'Norway' },
  { value: 'oman', label: 'Oman' },
  { value: 'pakistan', label: 'Pakistan' },
  { value: 'palau', label: 'Palau' },
  { value: 'palestine', label: 'Palestine' },
  { value: 'panama', label: 'Panama' },
  { value: 'papua_new_guinea', label: 'Papua New Guinea' },
  { value: 'paraguay', label: 'Paraguay' },
  { value: 'peru', label: 'Peru' },
  { value: 'philippines', label: 'Philippines' },
  { value: 'poland', label: 'Poland' },
  { value: 'portugal', label: 'Portugal' },
  { value: 'qatar', label: 'Qatar' },
  { value: 'romania', label: 'Romania' },
  { value: 'russia', label: 'Russia' },
  { value: 'rwanda', label: 'Rwanda' },
  { value: 'saint_kitts_and_nevis', label: 'Saint Kitts and Nevis' },
  { value: 'saint_lucia', label: 'Saint Lucia' },
  { value: 'saint_vincent_and_the_grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'samoa', label: 'Samoa' },
  { value: 'san_marino', label: 'San Marino' },
  { value: 'sao_tome_and_principe', label: 'Sao Tome and Principe' },
  { value: 'saudi_arabia', label: 'Saudi Arabia' },
  { value: 'senegal', label: 'Senegal' },
  { value: 'serbia', label: 'Serbia' },
  { value: 'seychelles', label: 'Seychelles' },
  { value: 'sierra_leone', label: 'Sierra Leone' },
  { value: 'singapore', label: 'Singapore' },
  { value: 'slovakia', label: 'Slovakia' },
  { value: 'slovenia', label: 'Slovenia' },
  { value: 'solomon_islands', label: 'Solomon Islands' },
  { value: 'somalia', label: 'Somalia' },
  { value: 'south_africa', label: 'South Africa' },
  { value: 'south_korea', label: 'South Korea' },
  { value: 'south_sudan', label: 'South Sudan' },
  { value: 'spain', label: 'Spain' },
  { value: 'sri_lanka', label: 'Sri Lanka' },
  { value: 'sudan', label: 'Sudan' },
  { value: 'suriname', label: 'Suriname' },
  { value: 'sweden', label: 'Sweden' },
  { value: 'switzerland', label: 'Switzerland' },
  { value: 'syria', label: 'Syria' },
  { value: 'taiwan', label: 'Taiwan' },
  { value: 'tajikistan', label: 'Tajikistan' },
  { value: 'tanzania', label: 'Tanzania' },
  { value: 'thailand', label: 'Thailand' },
  { value: 'timor-leste', label: 'Timor-Leste' },
  { value: 'togo', label: 'Togo' },
  { value: 'tonga', label: 'Tonga' },
  { value: 'trinidad_and_tobago', label: 'Trinidad and Tobago' },
  { value: 'tunisia', label: 'Tunisia' },
  { value: 'turkey', label: 'Turkey' },
  { value: 'turkmenistan', label: 'Turkmenistan' },
  { value: 'tuvalu', label: 'Tuvalu' },
  { value: 'uganda', label: 'Uganda' },
  { value: 'ukraine', label: 'Ukraine' },
  { value: 'united_arab_emirates', label: 'United Arab Emirates' },
  { value: 'united_kingdom', label: 'United Kingdom' },
  { value: 'united_states_of_america', label: 'United States of America' },
  { value: 'uruguay', label: 'Uruguay' },
  { value: 'uzbekistan', label: 'Uzbekistan' },
  { value: 'vanuatu', label: 'Vanuatu' },
  { value: 'vatican_city', label: 'Vatican City' },
  { value: 'venezuela', label: 'Venezuela' },
  { value: 'vietnam', label: 'Vietnam' },
  { value: 'yemen', label: 'Yemen' },
  { value: 'zambia', label: 'Zambia' },
  { value: 'zimbabwe', label: 'Zimbabwe' }
];

export const partnerOptions = {
  callerTunePartners: [ "Jio", "Airtel", "BSNL", "VI" ],
  indianStores: [ "Gaana", "Hungama", "Jiosaavn", "Wynk" ],
  internationalStores: [
    "7Digital", "MixUpload", "Deezer", "SoundCloud", "AMI Entertainment", "Simfy", "Slacker", "SoundExchange", "Gracenote", "Lickd", "8tracks", "Likee", "MonkingMe", "iMusica", "Appler Music", "TouchTunes", "Traxsource", "Pandora", "Tidal", "Juno Downloads", "Shazam", "SberZvuk", "Spotify", "BMAT", "KKBOX", "MediaNet", "Amazon", "Napster", "DailyMotion", "AWA", "iHeart Radio", "BoomPlay", "Facebook Audio Library", "Facebook Audio Footprinting", "Alibaba", "NetEase", "Tencent", "Audible Magic", "Muso.ai", "Saavn", "United Media Agency", "MixCloud", "Kuack Media Group", "SiriusXM", "Anghami", "Qobuz", "ClickNClear", "TunedGlobal", "FLO", "ACRCloud", "MoodAgent", "Enaza", "YouTube Art Tracks", "YouTube Content Id", "JOOX", "IPEX", "Jaxsta", "Melon", "Pretzel", "Resso", "TikTok", "SCPP", "Soundmouse", "Triller", "Yandex", "Zaycev", "AudioMack", "YouTube Music", "Instagram Reels", "Snapchat", "Bandcamp"
  ]
};
