export const genreOptions = [
  { value: "alternative", label: "Alternative" },
  { value: "alternative_rock", label: "Alternative Rock" },
  { value: "alternative_and_rock_latino", label: "Alternative & Rock Latino" },
  { value: "anime", label: "Anime" },
  { value: "baladas_y_boleros", label: "Baladas Y Boleros" },
  { value: "big_band", label: "Big Band" },
  { value: "blues", label: "Blues" },
  { value: "brazilian", label: "Brazilian" },
  { value: "c_pop", label: "C-Pop" },
  { value: "cantopop_hk_pop", label: "Cantopop/HK - Pop" },
  { value: "childrens", label: "Children's" },
  { value: "chinese", label: "Chinese" },
  { value: "christian", label: "Christian" },
  { value: "classical", label: "Classical" },
  { value: "comedy", label: "Comedy" },
  { value: "contemporary_latin", label: "Contemporary Latin" },
  { value: "country", label: "Country" },
  { value: "dance", label: "Dance" },
  { value: "easy_listening", label: "Easy Listening" },
  { value: "educational", label: "Educational" },
  { value: "electronic", label: "Electronic" },
  { value: "enka", label: "Enka" },
  { value: "experimental", label: "Experimental" },
  { value: "fitness_and_workout", label: "Fitness & Workout" },
  { value: "folk", label: "Folk" },
  { value: "french_pop", label: "French Pop" },
  { value: "german_pop", label: "German Pop" },
  { value: "german_folk", label: "German Folk" },
  { value: "hip_hop_rap", label: "Hip-Hop/Rap" },
  { value: "holiday", label: "Holiday" },
  { value: "instrumental", label: "Instrumental" },
  { value: "indo_pop", label: "Indo Pop" },
  { value: "inspirational", label: "Inspirational" },
  { value: "indian", label: "Indian" },
  { value: "indian_pop", label: "Indian Pop" },
  { value: "indian_rap", label: "Indian Rap" },
  { value: "indian_folk", label: "Indian Folk" },
  { value: "indian_bollywood", label: "Indian Bollywood" },
  { value: "indian_devotional_and_spiritual", label: "Indian Devotional & Spiritual" },
  { value: "indian_fusion", label: "Indian Fusion" },
  { value: "indian_gazal", label: "Indian Gazal" },
  { value: "indian_classical_vocal", label: "Indian Classical / Vocal" },
  { value: "indian_dance", label: "Indian Dance" },
  { value: "indian_electronic", label: "Indian Electronic" },
  { value: "jazz", label: "Jazz" },
  { value: "j_pop", label: "J-Pop" },
  { value: "k_pop", label: "K-Pop" },
  { value: "karaoke", label: "Karaoke" },
  { value: "latin_jazz", label: "Latin Jazz" },
  { value: "metal", label: "Metal" },
  { value: "new_age", label: "New Age" },
  { value: "opera", label: "Opera" },
  { value: "pop", label: "Pop" },
  { value: "punk", label: "Punk" },
  { value: "r_and_b", label: "R&B" },
  { value: "reggae", label: "Reggae" },
  { value: "reggaeton_y_hip_hop", label: "Reggaeton Y Hip-Hop" },
  { value: "regional_mexicano", label: "Regional Mexicano" },
  { value: "rock", label: "Rock" },
  { value: "salas_y_topical", label: "Salas Y Topical" },
  { value: "soul", label: "Soul" },
  { value: "soundtrack", label: "Soundtrack" },
  { value: "spoken_word", label: "Spoken Word" },
  { value: "thai_pop", label: "Thai Pop" },
  { value: "trot", label: "Trot" },
  { value: "vocal_nostalgia", label: "Vocal/Nostalgia" },
  { value: "world", label: "World" },
];

export const moodOptions = [
  { value: "uplifting", label: "Uplifting" },
  { value: "melancholic", label: "Melancholic" },
  { value: "euphoric", label: "Euphoric" },
  { value: "nostalgic", label: "Nostalgic" },
  { value: "romantic", label: "Romantic" },
  { value: "cinematic", label: "Cinematic" },
  { value: "aggressive", label: "Aggressive" },
  { value: "chill_mellow", label: "Chill / Mellow" },
  { value: "dark_moody", label: "Dark / Moody" },
  { value: "hopeful", label: "Hopeful" },
  { value: "tense_suspenseful", label: "Tense / Suspenseful" },
  { value: "playful_quirky", label: "Playful / Quirky" },
  { value: "energetic_high_tempo", label: "Energetic / High Tempo" },
  { value: "inspirational", label: "Inspirational" },
  { value: "mysterious", label: "Mysterious" },
  { value: "sad_reflective", label: "Sad / Reflective" },
  { value: "spiritual_devotional", label: "Spiritual / Devotional" },
  { value: "groovy_funky", label: "Groovy / Funky" },
  { value: "tribal_rooted", label: "Tribal / Rooted" },
  { value: "anthemic_epic", label: "Anthemic / Epic" },
];

export const languageOptions = [
  { value: "instrumental", label: "Instrumental" },
  { value: "afrikaans", label: "Afrikaans" },
  { value: "albanian", label: "Albanian" },
  { value: "amharic", label: "Amharic" },
  { value: "arabic", label: "Arabic" },
  { value: "aragonese", label: "Aragonese" },
  { value: "armenian", label: "Armenian" },
  { value: "asturian", label: "Asturian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "basque", label: "Basque" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bengali", label: "Bengali" },
  { value: "bosnian", label: "Bosnian" },
  { value: "breton", label: "Breton" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "catalan", label: "Catalan" },
  { value: "central_kurdish", label: "Central Kurdish" },
  { value: "chinese", label: "Chinese" },
  { value: "corsican", label: "Corsican" },
  { value: "croatian", label: "Croatian" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "dutch", label: "Dutch" },
  { value: "english", label: "English" },
  { value: "english_australia", label: "English (Australia)" },
  { value: "english_canada", label: "English (Canada)" },
  { value: "english_india", label: "English (India)" },
  { value: "english_us", label: "English (US)" },
  { value: "english_uk", label: "English (UK)" },
  { value: "english_new_zealand", label: "English (New Zealand)" },
  { value: "english_south_africa", label: "English (South Africa)" },
  { value: "estenian", label: "Estenian" },
  { value: "fareese", label: "Fareese" },
  { value: "filipino", label: "Filipino" },
  { value: "finnish", label: "Finnish" },
  { value: "french", label: "French" },
  { value: "galician", label: "Galician" },
  { value: "georgian", label: "Georgian" },
  { value: "german", label: "German" },
  { value: "gurani", label: "Gurani" },
  { value: "gujrati", label: "Gujrati" },
  { value: "hausa", label: "Hausa" },
  { value: "hawaiian", label: "Hawaiian" },
  { value: "hebrew", label: "Hebrew" },
  { value: "hindi", label: "Hindi" },
  { value: "hungarian", label: "Hungarian" },
  { value: "icelandic", label: "Icelandic" },
  { value: "indonesian", label: "Indonesian" },
  { value: "interlingua", label: "Interlingua" },
  { value: "irish", label: "Irish" },
  { value: "italian", label: "Italian" },
  { value: "japanese", label: "Japanese" },
  { value: "kannada", label: "Kannada" },
  { value: "kazakh", label: "Kazakh" },
  { value: "khmer", label: "Khmer" },
  { value: "koren", label: "Koren" },
  { value: "kurdish", label: "Kurdish" },
  { value: "kyrgyz", label: "Kyrgyz" },
  { value: "lao", label: "Lao" },
  { value: "latin", label: "Latin" },
  { value: "latvian", label: "Latvian" },
  { value: "lingala", label: "Lingala" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malay", label: "Malay" },
  { value: "malayalam", label: "Malayalam" },
  { value: "maltese", label: "Maltese" },
  { value: "marathi", label: "Marathi" },
  { value: "mongolian", label: "Mongolian" },
  { value: "nagpuri", label: "Nagpuri" },
  { value: "nepali", label: "Nepali" },
  { value: "norwegian", label: "Norwegian" },
  { value: "occitan", label: "Occitan" },
  { value: "oriya", label: "Oriya" },
  { value: "oromo", label: "Oromo" },
  { value: "pashto", label: "Pashto" },
  { value: "persian", label: "Persian" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "punjabi", label: "Punjabi" },
  { value: "quechua", label: "Quechua" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "sainthili", label: "Sainthili" },
  { value: "scottish", label: "Scottish" },
  { value: "serbian", label: "Serbian" },
  { value: "sindhi", label: "Sindhi" },
  { value: "shono", label: "Shono" },
  { value: "sinhala", label: "Sinhala" },
  { value: "slovak", label: "Slovak" },
  { value: "slovernian", label: "Slovernian" },
  { value: "somali", label: "Somali" },
  { value: "spanish", label: "Spanish" },
  { value: "sundanese", label: "Sundanese" },
  { value: "swahili", label: "Swahili" },
  { value: "swedish", label: "Swedish" },
  { value: "tajik", label: "Tajik" },
  { value: "tamil", label: "Tamil" },
  { value: "tatar", label: "Tatar" },
  { value: "telugu", label: "Telugu" },
  { value: "thai", label: "Thai" },
  { value: "tigrinya", label: "Tigrinya" },
  { value: "tongan", label: "Tongan" },
  { value: "turkish", label: "Turkish" },
  { value: "turkmen", label: "Turkmen" },
  { value: "twi", label: "Twi" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "urdu", label: "Urdu" },
  { value: "uyghur", label: "Uyghur" },
  { value: "uzbek", label: "Uzbek" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "walloon", label: "Walloon" },
  { value: "wetish", label: "Wetish" },
  { value: "western_frisian", label: "Western Frisian" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yiddish", label: "Yiddish" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zulu", label: "Zulu" },
];

export const themeOptions = [
  { value: "love_romance", label: "Love & Romance" },
  { value: "heartbreak_healing", label: "Heartbreak & Healing" },
  { value: "rebellion_resistance", label: "Rebellion & Resistance" },
  { value: "celebration_party", label: "Celebration & Party" },
  { value: "spiritual_devotional", label: "Spiritual & Devotional" },
  { value: "coming_of_age", label: "Coming-of-Age" },
  { value: "friendship_brotherhood", label: "Friendship & Brotherhood" },
  { value: "nature_environment", label: "Nature & Environment" },
  { value: "festival_tradition", label: "Festival & Tradition" },
  { value: "identity_self_discovery", label: "Identity & Self-Discovery" },
  { value: "urban_life_hustle", label: "Urban Life & Hustle" },
  { value: "nostalgia_memory", label: "Nostalgia & Memory" },
  { value: "hope_resilience", label: "Hope & Resilience" },
  { value: "journey_travel", label: "Journey & Travel" },
  { value: "family_legacy", label: "Family & Legacy" },
  { value: "social_justice_awareness", label: "Social Justice & Awareness" },
  { value: "fantasy_imagination", label: "Fantasy & Imagination" },
  { value: "ritual_culture", label: "Ritual & Culture" },
  { value: "empowerment_confidence", label: "Empowerment & Confidence" },
  { value: "mystery_suspense", label: "Mystery & Suspense" },
];

export const vocalsPresentOptions = [
  { value: true, label: 'Yes' },
  { value: false, label: 'No' },
];

export const syncClearedOptions = [
  { value: true, label: 'Yes' },
  { value: false, label: 'No' },
  { value: 'unsure', label: 'Unsure (Request assistance)' },
];

export const storeOptions = [
  { value: 'select_all', label: 'Select All' },
  { value: 'Spotify', label: 'Spotify' },
  { value: 'Apple Music', label: 'Apple Music' },
  { value: 'JioSaavn', label: 'JioSaavn' },
  { value: 'Amazon Music', label: 'Amazon Music' },
];

export const masterRightsOptions = [
  { value: 'artist', label: 'Artist' },
  { value: "label", label: "Label" },
  { value: "distributor", label: "Distributor" },
  { value: "other", label: "Other" },
];

export const publishingRightsOptions = [
  { value: "artist", label: "Artist" },
  { value: "publisher", label: "Publisher" },
  { value: "co_writer_s", label: "Co-writer(s)" },
  { value: "pro_registered", label: "PRO Registered" },
];

export const territoryOptions = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
  'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)', 'Costa Rica', 'Cote divoire', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
  'Democratic Republic of the United States of America', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
  'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini (formerly Swaziland)', 'Ethiopia',
  'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
  'Haiti', 'Honduras', 'Hungary',
  'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
  'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
  'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar (formerly Burma)',
  'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia (formerly Macedonia)', 'Norway',
  'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar',
  'Romania', 'Russia', 'Rwanda',
  'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
  'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan',
  'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe'
];

export const partnerOptions = {
  callerTunePartners: [ "Jio", "Airtel", "BSNL", "VI" ],
  indianStores: [ "Gaana", "Hungama", "Jiosaavn", "Wynk" ],
  internationalStores: [
    "7Digital", "MixUpload", "Deezer", "SoundCloud", "AMI Entertainment", "Simfy", "Slacker", "SoundExchange", "Gracenote", "Lickd", "8tracks", "Likee", "MonkingMe", "iMusica", "Appler Music", "TouchTunes", "Traxsource", "Pandora", "Tidal", "Juno Downloads", "Shazam", "SberZvuk", "Spotify", "BMAT", "KKBOX", "MediaNet", "Amazon", "Napster", "DailyMotion", "AWA", "iHeart Radio", "BoomPlay", "Facebook Audio Library", "Facebook Audio Footprinting", "Alibaba", "NetEase", "Tencent", "Audible Magic", "Muso.ai", "Saavn", "United Media Agency", "MixCloud", "Kuack Media Group", "SiriusXM", "Anghami", "Qobuz", "ClickNClear", "TunedGlobal", "FLO", "ACRCloud", "MoodAgent", "Enaza", "YouTube Art Tracks", "YouTube Content Id", "JOOX", "IPEX", "Jaxsta", "Melon", "Pretzel", "Resso", "TikTok", "SCPP", "Soundmouse", "Triller", "Yandex", "Zaycev", "AudioMack", "YouTube Music", "Instagram Reels", "Snapchat", "Bandcamp"
  ]
};
